### PR TITLE
Fixes #145: `Content-encoding` support is missing

### LINKED ISSUE #145: `Content-encoding` support is missing
`Content-Encoding` support is missing completely, that makes tests for case with e.g. gzip compressed files fail.

PR will follow shortly.

### PR DESCRIPTION
**Pull request by 412b**
## Description
`Content-Encoding` was completely missing.
- added content-encoding field
- cleaned up some content-type issues
- modified tests for check of the new functionality

## Related Issue
Fixes #145: `Content-encoding` support is missing

## Tasks

- [x] I have signed the [CLA](http://adobe.github.io/cla.html).
- [x] I have written tests and verified that they fail without my change.

### CODE REVIEW

File: server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java [hunk 1]
```diff
@@ -79,7 +79,7 @@
   private static final String META_FILE = "metadata";
   private static final String DATA_FILE = "fileData";
   private static final String PART_SUFFIX = ".part";
-  private static final String DEFAULT_CONTENT_TYPE = "application/octet-stream";
+  private static final String DEFAULT_CONTENT_TYPE = "binary/octet-stream";
```
Comment (agudian) [inline server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java]: Is that the default that is used by AWS S3 as well?

Comment (412b) [reply server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java]: yep, e.g. [here](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html)

**Comment by agudian** [comment]
Okay, let me know if you want to add a small IT as well.

I'll merge / release it then. 👍

**Comment by 412b** [comment]
@agudian I'll add some checks to `com.adobe.testing.s3mock.its.AmazonClientUploadIT`

**Comment by 412b** [comment]
@agudian checks added, if that's sufficient I'll squash and force-push

**Comment by agudian** [comment]
Looks great! I can directly squash it here in GitHub :)

**Comment by agudian** [comment]
Release is building... give it a couple minutes to show up on Docker Hub and a bit longer for Maven Central.

**Comment by 412b** [comment]
great :+1:
